### ISSUE TITLE
Unknown extension key in a translation string: org.example.myextension

### ISSUE THREAD

**Issue by freeform-sg** [Skvare/com.skvare.membershipextra#3]
Line 29 in MembershipType.extra.tpl has the following:

Unknown extension key in a translation string: org.example.myextension

`{crmScope extensionKey='org.example.myextension'}`

Pretty sure this just needs to change to:

`{crmScope extensionKey='com.skvare.membershipextra'}`

**Comment by sunilpawar** [comment]
@freeform-sg thanks for report. i have fixed issue.

**Comment by freeform-sg** [comment]
Awesome, thanks!
